--- #YAML:1.0
name:                POE-Component-Generic
version:             0.1100
abstract:            Generic non-blocking POE interface to any OO-module
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Carp:                          0
    Devel::Symdump:                2
    POE:                           0.31
    Scalar::Util:                  1
    Test::More:                    0.32
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Philip Gwyn <gwyn@cpan.org>
