# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-Client-DAAP
version:      0.01
version_from: lib/POE/Component/Client/DAAP.pm
installdirs:  site
requires:
    Carp:                          
    Devel::Symdump:                
    Net::DAAP::Client:                   
    POE:                           0.31
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
