# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-Generic
version:      0.07
version_from: lib/POE/Component/Generic.pm
installdirs:  site
requires:
    Carp:                          
    Devel::Symdump:                
    POE:                           0.31
    Scalar::Util:                  
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
